Update MAX_COUNT to be the maximum number of allowed by PutRecords
NerdWalletOSS/kinesis-python pull request #13
Opened 2018-03-15 16:39 UTC by langseth

According to AWS documentation[1], when putting multiple records in a single call
the maximum number of records are 500 for a single call. The previous count was based
off of the max rate that kinesis shard can handle

[1] https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html

2018-03-15 17:59 UTC, langseth commented
A bit more information here is the relevant documentation from the URL:
> Each PutRecords request can support **up to 500 records**. Each record in the request can be as large as 1 MB, up to a limit of 5 MB for the entire request, including partition keys. Each shard can support writes up to 1,000 records per second, up to a maximum data write total of 1 MB per second.

-- https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html

Regardless of the message rate, which can be fixed by backing off and retrying, going over the 500 record limit for a single PutRecords call will always fail.

2018-03-24 21:24 UTC, borgstrom requested changes
Thanks for this.  I agree with your changes, thanks for linking to the docs.  One small change to get the build passing and we can merge it.

2018-03-24 21:24 UTC, borgstrom commented on src/kinesis/producer.py
> +    MAX_COUNT = 500
Please remove the trailing whitespace here.  The CI job is failing because the linter is complaining about it.

2018-10-10 15:01 UTC, borgstrom approved these changes

2018-11-02 10:00 UTC, ibnbay00 commented
Not merged yet?

2018-11-26 22:37 UTC, merged